FROM node:20-alpine

# Menginstall dependencies yang diperlukan
RUN apk add --no-cache libc6-compat bash

# Buat direktori aplikasi
WORKDIR /app

# Menyalin package.json dan package-lock.json
COPY package*.json ./

# Menginstall dependencies development
RUN npm install

# Menyalin semua file
COPY . .

# Expose port
EXPOSE 3000

# Mendefinisikan health check
HEALTHCHECK --interval=10s --timeout=10s --start-period=30s --retries=3 CMD wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1

# Command untuk development
CMD ["npm", "run", "dev"]